version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: social_db
    restart: unless-stopped
    env_file:
      - ./db/.env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - social_net

  auth-service:
    build:
      context: ./auth-service
      args:
        - PORT=4000
    env_file:
      - ./auth-service/.env
    ports:
      - "4000:4000"
    depends_on:
      - user-service
    networks:
      - social_net

  user-service:
    build:
      context: ./user-service
      args:
        - PORT=3001
    env_file:
      - ./user-service/.env
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - social_net

  post-service:
    build:
      context: ./post-service
      args:
        - PORT=3002
    env_file:
      - ./post-service/.env
    ports:
      - "3002:3002"
    depends_on:
      - db
      - auth-service
      - user-service
    networks:
      - social_net

  likes-service:
    build:
      context: ./likes-service
      args:
        - PORT=4002
    env_file:
      - ./likes-service/.env
    ports:
      - "4002:4002"
    depends_on:
      - db
      - auth-service
    networks:
      - social_net

volumes:
  db_data:

networks:
  social_net:
    driver: bridge
