FROM node:18-alpine
WORKDIR /app

# Copiamos package.json y tsconfig para instalar dependencias
COPY package*.json tsconfig.json ./

RUN npm install

# Copiamos el código fuente
COPY ./src ./src

# Expone el puerto que usas en desarrollo
EXPOSE 3001

# Comando de arranque
CMD ["npm", "run", "dev"]
